image:
  repository: adminer
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: adminer.local
      paths:
        - path: /
          pathType: ImplementationSpecific