namespace: adminer
serviceName: adminer
image: adminer
imageTag: latest
replicas: 1
port: 8080
env: {}
storage:
  enabled: false
service:
  enabled: true
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  host: adminer.local
serviceAccount:
  enabled: false