{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.serviceName }}-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass | default "" }}
  hostPath:
    path: "/mnt/data/{{ .Values.serviceName }}"
{{- end }}