{{- if .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.env.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}