auth:
  username: airflow
  password: airflow
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: ImplementationSpecific

externalDatabase:
  host: postgres-postgresql.postgres
  user: postgres
  password: postgres
  database: airflow