executor: KubernetesExecutor


ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: Prefix


# External Postgres
data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: postgres-postgresql.postgres
    port: 5432
    db: airflow

# External Redis
externalRedis:
  enabled: true
  host: redis-master.redis
  port: 6379
  password: admin

# Disable internal Postgres and Redis
postgresql:
  enabled: false

redis:
  enabled: false

# Webserver settings
webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin


dags:
  persistence:
    enabled: false   # Disable the built-in DAGs persistence
  gitSync:
    enabled: false

extraVolumeMounts:
  - name: airflow-repo
    mountPath: /opt/airflow
    subPath: ""  # mount entire repo

extraVolumes:
  - name: airflow-repo
    persistentVolumeClaim:
      claimName: airflow-dags-pv

airflow:
  config:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins