auth:
  username: admin
  password: admin
  fernetKey: ""
  secretKey: ""
  jwtSecretKey: ""

executor: CeleryExecutor
loadExamples: false

dags:
  enabled: true
  existingConfigmap: "airflow-project"
  repositories: []

postgresql:
  enabled: false
redis:
  enabled: false

externalDatabase:
  host: "postgres-postgresql.postgres"
  user: "postgres"
  password: "postgres"
  database: "airflow"
  port: 5432

externalRedis:
  host: "redis-master.redis"