airflow:
  executor: CeleryExecutor
  username: admin
  password: admin
  loadExamples: true

auth:
  username: airflow
  password: airflow
web:
  baseUrl: airflow.local
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: airflow.local
      paths:
        - path: /
          pathType: ImplementationSpecific

externalDatabase:
  host: postgres-postgresql.postgres
  user: postgres
  password: postgres
  database: airflow