airflow:
  executor: LocalExecutor
  username: admin
  password: admin
  loadExamples: true

auth:
  username: airflow
  password: airflow
web:
  baseUrl: airflow.local
ingress:
  enabled: true
  ingressClassName: nginx
  hostname: airflow.local

postgresql:
  enabled: false
externalDatabase:
  host: postgres-postgresql.postgres
  user: postgres
  password: postgres
  database: airflow