executor: LocalExecutor

# External Postgres
data:
  metadataConnection:
    user: postgres
    pass: postgres
    protocol: postgresql
    host: postgres-postgresql.postgres
    port: 5432
    db: airflow

# External Redis
externalRedis:
  enabled: true
  host: redis-master.redis
  port: 6379
  password: admin

# Disable internal Postgres and Redis
postgresql:
  enabled: false

redis:
  enabled: false

# Webserver settings
webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin
