namespace: postgres
serviceName: postgres
image: postgres
imageTag: 16
replicas: 1
port: 5432
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
storage:
  enabled: true
  size: 10Gi
service:
  enabled: true
  type: ClusterIP
  port: 5432
ingress:
  enabled: false
serviceAccount:
  enabled: false