namespace: postgres
serviceName: postgres
image: postgres
imageTag: 15
replicas: 1
env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
storage:
  enabled: true
  size: 10Gi
service:
  enabled: true
  type: ClusterIP
  port: 5432
ingress:
  enabled: false